from datetime import datetime


def generate_job_comparison_report(ranked_jobs):
    """
    Generate a downloadable text report for
    multiple job comparison results.
    """

    report = []

    report.append("=" * 70)
    report.append("                         RESUMEIQ")
    report.append("              JOB MATCHING COMPARISON")
    report.append("=" * 70)

    report.append(
        f"\nGenerated: "
        f"{datetime.now().strftime('%d %B %Y, %I:%M %p')}"
    )

    report.append("\n")
    report.append("=" * 70)
    report.append("JOB MATCHING RESULTS")
    report.append("=" * 70)

    for rank, job in enumerate(ranked_jobs, start=1):

        report.append("")
        report.append(f"Rank #{rank}")
        report.append("-" * 70)

        report.append(f"Job Title: {job['title']}")
        report.append(f"Match Score: {job['score']}%")

    report.append("\n")
    report.append("=" * 70)
    report.append("ABOUT THIS SCORE")
    report.append("=" * 70)

    report.append(
        "The match score is calculated using TF-IDF and cosine "
        "similarity between the resume text and each job description."
    )

    report.append(
        "\nThe ranking represents the calculated text similarity "
        "within the jobs entered by the user."
    )

    report.append("\n")
    report.append("=" * 70)
    report.append("Generated by ResumeIQ")
    report.append("AI-Powered Resume Intelligence & Job Matching")
    report.append("=" * 70)

    return "\n".join(report)